c*id* rcwfn
      SUBROUTINE RCWFN ( RHO,ETA,MINL,MAXL,FC,FCP,GC,GCP,ACCUR, IRET )
C
C     COMPUTES REGULAR AND IRREGULAR COULOMB WAVEFUNCTIONS.
C
C   *****************************************************************
C   *                                                               *
C   * !!! THE APPROPRIATE DATA STATEMENTS MUST BE ACTIVATED !!!!    *
C   *   ci3e FOR IEEE machines (RS6000, ...)                        *
C   *   CIB FOR IBM 370 TYPE MACHINES                               *
C   *   CVA FOR VAX TYPE MACHINES WITH D-FORMAT                     *
C   *   CRA FOR CRAY TYPE MACHINES - DOUBLE PRECISION MUST BE       *
C   *          DISABLED IN THE COMPLILER INVOCATION                 *
C   *   CDC FOR CDC CYBER TYPE MACHINES  - DOUBLE PREC. FUNCTIONS   *
C   *          MUST BE CHANGED TO SINGLE                            *
C   *   CUN FOR UNIVAC 1108 TYPE MACHINES                           *
C   *                                                               *
C   *****************************************************************
C
C       THIS SUBROUTINE RETURNS THE REGULAR AND IRREGULAR COULOMB
C     WAVEFUNCTIONS AND THEIR DERIVATIVES FOR SPECIFIC VALUES OF
C     ETA AND RHO AND FOR A RANGE OF L'S.  THE RANGE OF L'S (ORBITAL
C     ANGULAR MOMENTUM) NEED NOT BEGIN AT L = 0 AND, IN GENERAL,
C     IT WILL BE LESS TIME CONSUMING TO REQUEST ONLY THOSE L'S
C     THAT ARE ACTUALLY DESIRED.  THE CONVENTIONS OF ABRAMOWITZ
C     AND STEGUN (HANDBOOK OF MATHEMATICAL FUNCTIONS) ARE USED.
C
C       THIS SUBROUTINE IS AN ADAPTATION OF THE MANCHESTER SUBROUTINE
C     OF THE SAME NAME (BUT SLIGHTLY DIFFERENT ARGUMENT LIST) THAT
C     WAS PUBLISHED IN COMPUTER PHYSICS COMMUNICATIONS 8, 377 (1974).
C     BY BARNETT, FENG, STEED AND GOLDFARB.  THE CONTINUED FRACTIONS
C     INTRODUCED IN THAT ARTICLE ARE USED IN THE RANGE RHO >
C     RHO(TURN) BUT COMPLETELY DIFFERENT PROCEDURES ARE USED
C     FOR RHO < RHO(TURN).  THE NEW PROCEDURES ALLOW RESULTS
C     FOR RHO < RHO(TURN) OF ACCURACY COMPARABLE TO THOSE FOR
C     RHO > RHO(TURN) IN COMPARABLE TIME.
C
C       ONE OF THE CONTINUED FRACTIONS IS NOT CONVERGENT FOR VERY
C     SMALL RHO AND THUS THIS ROUTINE WILL FIND ONLY F AND F' FOR
C     RHO < .005.  IN ADDITION THE ROUTINE BECOMES RATHER SLOW FOR
C     RHO < .1.  FOR VERY LARGE RHO ( >> 1000 ), ANOTHER CONTINUED
C     FRACTION CONVERGES VERY SLOWLY AND THE SUBROUTINE WILL FAIL
C     TO CONVERGE IN THE MAXIMUM ALLOWED NUMBER OF ITERATIONS FOR
C     RHO > 9500 WITH THE EXCEPTION THAT LARGER RHO ARE POSSIBLE
C     IF ETA IS NEAR RHO/2.
C
C       ASIDE FROM THE ABOVE LIMITATIONS, THE SUBROUTINE HAS A VERY
C     LARGE RANGE OF ETA,  RHO, AND L FOR WHICH IT WILL RETURN
C     RELIABLE VALUES IN REASONABLE TIMES.  IT HAS BEEN TESTED FOR
C     -2000 < ETA < 5000,  1E-6 < RHO < 10000;  0 < L < 1000 .
C     THE TESTS CONSISTED OF COMPARASONS TO EXISTING ROUTINES TO
C     LOCATE CODING ERRORS AND OF COMPARASONS TO QUADRUPLE PRECISION
C     RESULTS TO DETERMINE THE NUMERICAL STABILITY OF THE ALGORITHMS.
C     HOWEVER, NO VERIFICATION OF THE CORRECTNESS OF G OR G' FOR
C     ETA < 0 HAS BEEN MADE.
C
C
C     ARGUMENTS (ALL FLOATING POINT ARGUMENTS ARE DOUBLE PRECISION) -
C
C     RHO - THE VALUE OF THE RADIAL COORDINATE AT WHICH F, F', G, AND
C           G' ARE DESIRED.  0 < RHO < 9500 IS REQUIRED.  IF
C           RHO < .005, ONLY F AND F' WILL BE FOUND.
C
C     ETA - THE VALUE OF THE CHARGE PARAMETER TO BE USED.  THE ROUTINE
C           HAS BEEN TESTED FOR -2000 < ETA < 5000.  ETA = 0 WILL
C           RESULT IN THE COMPUTATION OF THE SPHERICAL BESSEL
C           FUNCTIONS TIMES RHO.
C
C     MINL - THE MINIMUM VALUE OF L FOR WHICH THE FUNCTIONS ARE DESIRED.
C     MAXL - THE MAXIMUM VALUE OF L.
C
C     FC, FCP, GC, AND GCP - THESE ONE DIMENSIONAL ARRAYS WILL BE
C           SET TO THE COMPUTED VALUES OF F, F', G, AND G' RESPECTIVELY.
C           EACH ARRAY MUST BE OF LENGTH AT LEAST MAXL+1 AND WILL
C           BE SET AS
C             ARRAY(L+1) = FUNCTION(L)   MINL =< L =< MAXL .
C           DEPENDING ON ETA AND RHO, THE FIRST MINL ELEMENTS OF
C           EACH ARRAY MAY BE USED FOR INTERMEDIATE COMPUTATIONS AND
C           THEIR VALUES ARE NOT PREDICTABLE UPON EXIT FROM RCWFN.
C
C     ACCUR - THE DESIRED ACCURACY OF CONVERGENCE OF THE CONTINUED
C          FRACTIONS AND OTHER SERIES.  IN GENERAL THIS WILL BE
C          THE RELATIVE ACCURACY OF THE FINAL VALUES EXCEPT NEAR
C          A ZERO OF ONE OF THE FUNCTIONS.  ACCUR SHOULD BE IN
C          THE RANGE
C              1E-6 < ACCUR < 1E-15 ,
C          IF IT IS NOT, ONE OF THE ABOVE TWO VALUES WILL BE USED.
C
C     IRET - THIS INTEGER IS SET TO A RETURN CODE TO INDICATE THAT
C          RCWFN WAS SUCCESSFUL OR THE REASON FOR FAILURE:
C        0 - ALL O.K.; ALL FUNCTIONS FOUND.
C        1 - SOME O.K., THOSE FOR HIGHER L'S HAVE UNDER/OVER-FLOWED
C        2 - RHO < .005; ONLY F, F' WERE COMPUTED.
C        3 - RHO < .005; ONLY F, F' WERE COMPUTED AND SOME OF THEM
C                        UNDERFLOWED.
C        4 - ALL WILL UNDER/OVER-FLOW; NO RESULTS DEFINED.
C        5 - FAILED TO AVOID DIVIDE BY ZERO IN F'/F LOOP
C        6 - NONCONVERGENCE OF R
C        7 - NONCONVERGENCE OF P + IQ
C        8 - NONCONVERGENCE OF MACLAUREN SERIES
C        9 - NONCONVERGENCE OF THE TAYLOR SERIES ABOUT RHO = 2*ETA
C     IRET'S OF 5 TO 9 SHOULD BE REPORTED TO STEVE PIEPER ( X4523 )
C
C       THE FOLLOWING TABLE GIVES SAMPLE EXECUTION TIMES ON THE
C     /75 AND /195.  TIMES ARE FOR ACCUR = 1D-14 AND FOR
C     MINL = MAXL = 0.  IN GENERAL EXECUTION TIME IS WEAKLY DEPENDANT
C     ON ACCUR AND MINL.  IF MAXL > MINL, THE TIMES REQUIRED FOR
C     EACH ADDITIONAL L ARE APPROXIMATLEY 0.01 MILLISEC ON THE /195
C     AND 0.15 MILLISEC ON THE /75.  TIMES FOR ETA < 0 ARE COMPARABLE TO
C     TO THOSE FOR \ETA\.  THE FINAL COLUMN OF THE TABLE GIVES
C     THE NUMBER OF BITS LOST DUE TO ROUND OFF AND TRUNCATION
C     ERRORS AND INDICATES THE MAXIMUM PRECISION POSSIBLE ON A
C     GIVEN MACHINE.  THE /360 AND /370 HAVE 56 BITS OF PRECISION
C     (16.8 DECIMAL PLACES) AND EACH 3.3 BITS LOST REPRESENTS
C     ONE DECIMAL PLACE LOST.
C
C      ETA    RHO     TIME IN MILLISECONDS    BITS LOST
C                       /195      /75
C
C        0.      .01     .15       1.2            3
C        0.     1.       .13       1.2            3
C        0.   100.      1.0       11.            11
C        0.  1000.      7.6       81.
C        1.      .1     5.4       81.             9
C        1.     1.      1.0       12.5            8
C        1.    10.       .33       3.7            3
C        1.   100.      1.1       11.
C        1.  1000.      8.1       81.
C       10.     1.      1.5       20.             6
C       10.    10.       .8        8.3            6
C      100.    75.      1.9       21.            10
C      100.   100.      2.0       21.            10
C      100.  1000.      7.3       74.            13
C     1000.  5000.     29.       385.            16
C
C
C     MAY 23, 1976 - REVISED VERSION BY S. PIEPER.
C     NOV 19, 1976 - FIX CHOICE OF ROOT FOR RHO << ETA, ETA > 10
C     12/14/77 - CDC VERSION USING MORTRAN
C     6/27/78 - FIX CDC VRYBIG, PRINTOUTS FOR ERROR CONDITIONS - S.P.
C     1/29/80 - CUN, CVA VERSIONS, CFR%F - RPG
C     3/13/80 - BACK TO CFR%F - S.P.
C     7/9/80 - CRAY DATA STATEMENST - S.P.
C     7/3/91 - RS6000 version
C
      IMPLICIT REAL*8 ( A-H, O-Z )
C
      DIMENSION FC(1),FCP(1),GC(1),GCP(1)
C
C     VRYBIG IS THE RESULT OF AN OVERFLOW
C     BIG IS REPRESENTATIVE OF MAX NUMBER, SMALL IS ITS INVERSE
C     SMALLN IS  LOG(SMALL)  (MUST BE ACCURATE)
C     PRECIS IS ABOUT  100*(MACHINE PRECISION)
C     PRECLN IS  > \LOG(MACHINE PRECISION)\
C     PRERT3 IS LIKE THE CUBEROOT OF THE MACHINE PRECISION
C
CIB      DATA VRYBIG / Z 7FFFFFFF FFFFFFFF /
CIB      DATA BIG / Z 70800000 00000000 /
CIB      DATA SMALL / Z 11200000 00000000 /
C     REAL*16 SMALLN / -132.39111148694955409869133519851171 Q+00 /
CIB      REAL*8 SMALLN / Z C284641FE1E589CC /
CIB      DATA PRERT3 / 1.D-7 /,  PRECIS / 1.D-15 /,  PRECLN / 44.D0 /
C
C     FOR CDC WE STOP BEFORE OVERFLOW SINCE CANNOT TRAP OVERFLOW
CDC      DATA VRYBIG / 3657 4000 0000 0000 0000 B /
CDC      DATA BIG / 3621 4000 0000 0000 0000 B /
CDC      DATA SMALL  / 0020 4000 0000 0000 0000 B /
CDC      DATA SMALLN / 6046 2632 2411 4172 5514 B /
CDC      DATA PRERT3 / 1.E-5 /,  PRECIS /1.E-12 /,
CDC     1  PRECLN / 35.E0 /
C
CRA      DATA VRYBIG / 1.E+2450 /
CRA      DATA BIG    / 1.E+2100 /
CRA      DATA SMALL  / 1.E-2100 /
CRA      DATA SMALLN / -4835.4286 9528 749 /
CRA      DATA PRERT3 / 1.E-5 /,  PRECIS / 1.E-12 /,
CRA     1  PRECLN / 35.E0 /
C
      DATA VRYBIG / 1.79769D+308 /
      DATA BIG    / 1.D+300 /
      DATA SMALL  / 1.D-300 /
      DATA SMALLN / -690.775527898214 /
      DATA PRERT3 / 2.7E-5 /,  PRECIS / 2.E-14 /,
     1  PRECLN / 32.E0 /
C
CUN      DATA VRYBIG / 1.D290 /, BIG / 1.D250 /, SMALL / 1.D-250 /
CUN      DATA SMALLN / -575.64627 32487 61421 0D0 /
CUN      DATA PRERT3 / 1.D-7 /, PRECIS / 1.D-16 /, PRECLN / 44.D0 /
C
CVA      DATA VRYBIG / 1.D32 /, BIG / 1.D25 /, SMALL / 1.D-25 /
CVA      DATA SMALLN / -57.564627 32487 61421 0D0 /
CVA      DATA PRERT3 / 1.D-7 /, PRECIS / 1.D-15 /, PRECLN / 44.D0 /
C
CXX      REAL*16 PI / 3.1415926535897932384626433832795028 0Q+00 /
      REAL*8  PI / 3.141592653589793238                 0D+00 /
CIB      DATA PI / Z 413243F6A8885A31 /
C
      LOGICAL FRSTSW
C
C
C     COULOMB WAVEFUNCTIONS CALCULATED AT RHO = RHO BY THE
C     CONTINUED-FRACTION METHOD OF STEED   MINL,MAXL ARE ACTUAL L-VALUES
C     SEE BARNETT FENG STEED AND GOLDFARB COMPUTER PHYSICS COMMON 1974
C
C
C     HERE WE LIMIT ACCURACY TO REASONABLE VALUES FOR THE MACHINE
C
      ACC  = ACCUR
      ACC = MAX( ACC, PRECIS )
      ACC = MIN( ACC, PRERT3 )
C
      LMAX = MAXL
      LMIN = MINL
      LMIN1= LMIN + 1
      XLL1 = LMIN*LMIN1
      ETA2 = ETA*ETA
C
C     DETERMIN WHICH REGION WE ARE IN
C
C     FOR RHO < .45, Q OF P+IQ IS POORLY DETERMINED SO WE DON'T USE IT.
C     EXCEPT THAT FOR LARGE NEGATIVE ETA THE MACLAUREN SERIES ALSO
C     HAS PROBLEMS
C
      IF ( RHO .GT. .45D0 )  GO TO 20
      IF ( ETA .GE. 0 )  GO TO 10
      IF ( -ETA*RHO .GT. 7 )  GO TO 20
C
C     FOR RHO < .005, WE ONLY RETURN F AND F' SINCE THE P+IQ RECURSION
C     IS VERY SLOWLY CONVERGENT  ( FOR VERY SMALL ETA IT IS POSSIBLE
C     TO GO TO SMALLER RHO ( RHO > 1E+4*ETA )  BUT WE IGNOR THAT HERE.
C
 10   IF ( RHO .GT. .005D0 )  GO TO 60
      IGOTO = 5
      GO TO 70
C
 20   TURN = ETA + SQRT(ETA2 + XLL1)
      IGOTO = 1
      IF ( RHO .GE. TURN-1.D-4 )  GO TO 100
C
C     WE ARE INSIDE THE TURNING POINT FOR MINL, CAN WE GET OUTSIDE
C     OF IT BY REDUCING MINL. (THIS IS ALWAYS POSSIBLE FOR
C     ETA < 0).
C
      IF ( RHO .LT. ETA+ABS(ETA) )  GO TO 60
C
C     YES, DO SO - THIS IS THE SAME AS  RHO > RHO(TURN)  EXCEPT
C     WE GENERATE SOME EXTRA F(L), G(L) FOR  L < MINL
C
      LMIN = .5*( SQRT(1+4*((RHO-ETA)**2-ETA2)) - 1 )
      LMIN1 = LMIN + 1
      GO TO 80
C
C     MUST USE A DIFFERENT METHOD TO SUPPLIMENT THE BAD I Q
C     VALUE.  ALWAYS START WITH LMIN = 0 FOR SIMPLICITY.
C
C     NOTE ONLY ETA > 0 GETS TO HERE ( EXCEPT WHEN RHO < .45 )
C
 60   IGOTO = 2
 70   LMIN = 0
      LMIN1 = 1
      IF ( ETA .LT. 10  .OR.  RHO .LE. ETA )  GO TO 80
      IGOTO = 3
C
 80   XLL1 = LMIN*LMIN1
C
C     HERE WE COMPUTE  F'/F  FOR L = MAXL
C     WE THEN RECURSE DOWN TO LMIN TO GENERATE THE UNNORMALIZED F'S
C     THIS SECTION IS USED FOR ALL RHO.
C
 100  PL   = LMAX + 1
      RHOUSE = RHO
 105  PLSAVE = PL
 110  FRSTSW = .TRUE.
C     CONTINUED FRACTION FOR  R = FP(MAXL)/F(MAXL)
      R  = ETA/PL + PL/RHOUSE
      DQ  = (ETA*RHOUSE)*2.0 + 6*PL**2
      DR = 12*PL + 6
      DEL = 0.0
      D   = 0.0
      F   = 1.0
      X   = (PL*PL - PL + (ETA*RHOUSE))*(2.0*PL - 1.0)
      AI = RHOUSE*PL**2
      DI = (2*PL+1)*RHOUSE
C
C     LOOP AND CONVERGE ON R
C
      DO 139  I = 1, 100000
         H = (AI + RHOUSE*ETA2)*(RHOUSE - AI)
         X   = X + DQ
         D = D*H + X
C
C     IF WE PASS NEAR A ZERO OF THE DIVISOR, START OVER AT
C     LARGER LMAX
C
         IF ( ABS(D) .GT. PRERT3*ABS(DR) )  GO TO 130
         PL = PL + 1
         IF ( PL .LT. PLSAVE+10 )  GO TO 110
         IRET = 5
      GO TO 990
C
 130     D = 1/D
         DQ = DQ + DR
         DR = DR + 12
         AI = AI + DI
         DI = DI + 2*RHOUSE
         DEL =  DEL*(D*X - 1.0)
         IF (FRSTSW) DEL = -RHOUSE*(PL*PL + ETA2)*(PL + 1.0)*D/PL
         FRSTSW = .FALSE.
         R  = R + DEL
         IF(D.LT.0.0) F = -F
         IF ( ABS(DEL) .LT. ABS(R*ACC) )  GO TO 140
 139  CONTINUE
      IRET = 6
      GO TO 990
C
C     R HAS CONVERGED;  DID WE INCREASE LMAX
C
 140  IF ( PL .EQ. PLSAVE )  GO TO 160
C
C     RECURSE DOWN ON R TO LMAX
C     HERE THE ONLY PART OF F THAT IS OF INTEREST IS THE SIGN
C
      PL = PL-1
 150     D = ETA/PL + PL/RHOUSE
         F = (R+D)*F
         R = D - (1+ETA2/PL**2)/(R+D)
         PL = PL - 1
         IF ( PL .GT. PLSAVE )  GO TO 150
C
C     NOW HAVE R(LMAX, RHO) OR IF IGOTO=4, R(LMIN, 2*ETA)
C
 160  IF ( IGOTO .EQ. 4 )  GO TO 210
      FC (LMAX+1) = F
      FCP(LMAX+1) = F*R
      IF( LMAX.EQ.LMIN) GO TO 200
C     DOWNWARD RECURSION TO LMIN FOR F AND FP, ARRAYS GC,GCP ARE STORAGE
      L  = LMAX
      PL = LMAX
      AR = 1/RHO
      DO 189 LP  = LMIN1,LMAX
         GC (L+1) = ETA/PL + PL*AR
         GCP(L+1) = SQRT( (ETA/PL)**2 + 1 )
         FC (L)   = (GC(L+1)*FC(L+1) + FCP(L+1))/GCP(L+1)
         FCP(L)   =  GC(L+1)*FC(L)   - GCP(L+1)*FC(L+1)
         PL = PL - 1
         L  = L - 1
C
C     IF WE ARE GETTING NEAR AN OVERFLOW, RENORMALIZE EVERYTHING DOWN
C
         IF ( ABS(FC(L+1)) .LT. BIG )  GO TO 189
         DO 179  LL = L, LMAX
            FC(LL+1) = SMALL*FC(LL+1)
            FCP(LL+1) = SMALL*FCP(LL+1)
 179     CONTINUE
 189  CONTINUE
      F  = FC (LMIN1)
      R = FCP(LMIN1)/F
C
C     HERE WE FIND
C        P + IQ  =  (G'+IF')/(G+IF)
C     THIS SECTION IS USED IN ALL CASES EXCEPT WHEN
C        15 < ETA < RHO < 2*ETA
C
 200  IF ( IGOTO .EQ. 3 )  GO TO 500
      IF ( IGOTO .EQ. 5 )  GO TO 400
C
C     NOW OBTAIN P + I.Q FOR LMIN FROM CONTINUED FRACTION (32)
C     REAL ARITHMETIC TO FACILITATE CONVERSION TO IBM USING REAL*8
 210  P  = 0.0
      Q  = RHOUSE - ETA
      PL = 0.0
      AR = -(ETA2 + XLL1)
      AI =   ETA
      BR = Q + Q
      BI = 2.0
      WI = ETA + ETA
      DR =   BR/(BR*BR + BI*BI)
      DI =  -BI/(BR*BR + BI*BI)
      DP = -(AR*DI + AI*DR)
      DQ =  (AR*DR - AI*DI)
C
C     LOOP AND CONVERGE ON P + IQ
C
 230     P  =  P + DP
         Q  =  Q + DQ
         PL = PL + 2.0
         AR = AR + PL
         AI = AI + WI
         BI = BI + 2.0
         D  = AR*DR - AI*DI + BR
         DI = AI*DR + AR*DI + BI
         T  = 1.0/(D*D + DI*DI)
         DR =  T*D
         DI = -T*DI
         H  = BR*DR - BI*DI - 1.0
         X  = BI*DR + BR*DI
         T  = DP*H  - DQ*X
         DQ = DP*X  + DQ*H
         DP = T
         IF(PL.GT.46000.) GO TO 920
         IF(ABS(DP)+ABS(DQ).GE.(ABS(P)+ABS(Q))*ACC) GO TO 230
      P  = P/RHOUSE
      Q  = Q/RHOUSE
C
C     WE NOW HAVE  R  AND  P+IQ,  IS THIS ENOUGH
C
      IF ( IGOTO .EQ. 2 )  GO TO 400
C
C     SOLVE FOR FP,G,GP AND NORMALISE F  AT L=LMIN
C
C     SINCE THIS IS FOR  RHO > RHO(TURN), F AND G ARE REASONABLE
C     NUMBERS
C
      X = (R-P)/Q
      FMAG = SQRT( 1/(Q*(1+X**2)) )
      W = FMAG/ABS(F)
      F = W*F
      G = F*X
      GP = R*G - 1/F
      IF ( IGOTO .EQ. 4 )  GO TO 600
      GO TO 800
C
C     HERE   RHO < ETA  OR  RHO < 2*ETA < 20  OR  RHO < .45
C     WE USE THE MACLAUREN SERIES TO GET  F( L=0, ETA, RHO )
C
C     FIRST COMPUTE  RHO*C(L=0, ETA)
C
 400  C = 2*PI*ETA
      IF ( ABS(C) .GT. .5 )  GO TO 410
C
C     USE MACLAURIN EXPANSION OF  X / (EXP(X)-1)
C
      X = 0
      T = 1
      AR = 1
      BR = C
      AI = 1
      C = 1
 405     AI = AI + 1
         AR = AR*BR/AI
         C = C + AR
         IF ( ABS(AR) .GE. ACC*C )  GO TO 405
      C = 1/C
      GO TO 430
C
C     HERE ETA IS NOT TINY.
C
 410  IF ( ETA .GT. 0 )  GO TO 420
      C = -C
      X = 0
      T = 1
      GO TO 425
 420  X = -SMALLN - PI*ETA
      T = SMALL
 425  IF ( C .LT. PRECLN )  C = C / (1-EXP(-C))
 430  C = RHO*SQRT(C)
      B1 = 1
      B2 = ETA*RHO
      SUM = B1 + B2
      AI = 6
      DI = 6
      DO 449  I = 1, 10000
         B3 = ( (2*ETA*RHO)*B2 - (RHO**2)*B1 ) / AI
         AI = AI + DI
         DI = DI + 2
         SUM = SUM + B3
         STOP = ABS(B1) + ABS(B2) + ABS(B3)
         B1 = B2
         B2 = B3
         IF ( ABS(SUM) .LT. BIG )  GO TO 445
         X = X - SMALLN
         SUM = SUM*SMALL
         B1 = B1*SMALL
         B2 = B2*SMALL
 445     IF ( STOP .LT. ACC*ABS(SUM) )  GO TO 450
 449  CONTINUE
      IRET = 8
      GO TO 990
C
 450  SUM = ( C*EXP(X)*SUM ) * T
C
C     DID IT UNDERFLOW
C
      IF ( SUM .EQ. 0 )  GO TO 900
C
C     WE NOW HAVE  F (=SUM),  R,  AND P  ( P ONLY IF RHO > .005 )
C     USE THE WRONSKIAN AS THE 4TH CONDITION
C
      W = SUM/F
      F = SUM
      IF ( IGOTO .EQ. 5 )  GO TO 850
      X = (R-P)*F
      IF ( ABS(X) .GT. PRERT3 )  GO TO 480
C
C     HERE F**3 AND F**4 TERMS ARE LESS THAN MACHINE PRECISION
C
      G = 1/X
      GP = P*G
      GO TO 800
C
C     HERE WE MUST INCLUDE F**3, F**4; WE MUST ALSO WORRY ABOUT
C     WHICH SIGN OF THE ROOT TO USE.
C     THE POSITIVE ROOT APPLIES FOR G > F; ELSE THE NEGATIVE ROOT
C     WE USE Q IN DETERMINING WHICH IS CORRECT
C
 480  B1 = .5/X
      B2 = B1 * SQRT(1-4*(X*F)**2)
      G = B1 + B2
C     G > F IN ALL OF REGION 2 FOR ETA > 0
      IF ( ETA .GE. 0 )  GO TO 490
      SUM = 1/Q - F**2
      GP = B1 - B2
      IF ( ABS(G**2-SUM) .GT. ABS(GP**2-SUM) )  G = GP
 490  GP = P*G - X*F/G
      GO TO 800
C
C     ETA > 15  AND  ETA < RHO < 2*ETA
C
C     WE FIND G AND G' FOR LMIN, RHO=2*ETA USING THE ABOVE METHOD
C     CONSISTING OF R, P+IQ, AND W.
C
 500  RHOUSE = ETA+ETA
      PL = LMIN+1
      IGOTO = 4
      GO TO 105
C
C     NOW WE HAVE  G, G'  AT THE TURNING POINT, GO IN USING TAYLOR
C
C
 600  DEL = RHOUSE - RHO
      B1 = G
      B2  = -DEL*GP
      B3 = 0
      G = B1+B2
      ACCR = ACC/2
      DELINV = -1/DEL
      DFACTR = 3*DELINV
      X = DEL/RHOUSE
      AI = X+X
      DI = AI+AI
      AR = 6
      DR = 6
      DO 639  I = 1, 10000
         S = ( AI*B3 + (X*DEL**2)*B1 ) / AR
         AR = AR + DR
         DR = DR + 2
         AI = AI + DI
         DI = DI + 2*X
         G = G + S
         GP = GP + DFACTR*S
         IF ( G .GE. VRYBIG )  GO TO 900
         DFACTR = DFACTR + DELINV
         B1 = B2
         B2 = B3
         B3 = S
         IF ( S .LT. ACCR*G )  GO TO 650
 639  CONTINUE
      IRET = 9
      GO TO 990
C
C     HERE WE HAVE  R = F'/F,  G,  G'
C     USE WRONSKIAN AS THE 4TH CONDITION
C
 650  F = FC(LMIN1)
      R = FCP(LMIN1)/F
      SUM = 1/(R*G-GP)
      W = SUM/F
      F = SUM
C
C     WE NOW HAVE  F, R = F'/F, G, G'  AT LMIN
C
C     UPWARD RECURSION FROM GC(LMIN) AND GCP(LMIN),STORED VALUES ARE RHO
C     RENORMALISE FC,FCP FOR EACH L-VALUE
C
 800  GC (LMIN1) = G
      GCP(LMIN1) = GP
      FC(LMIN1) = F
      FCP(LMIN1) = R*F
      IRET = 0
      IF(LMAX.EQ.LMIN)  RETURN
      DO  829  L = LMIN1,LMAX
         T        = GC(L+1)
         GC (L+1) = (GC(L)*GC (L+1) - GCP(L))/GCP(L+1)
         GCP(L+1) =  GC(L)*GCP(L+1) - GC(L+1)*T
         FC (L+1) = W*FC (L+1)
 829     FCP(L+1) = W*FCP(L+1)
 840  IF ( ABS(FC(LMAX+1))+ABS(FCP(LMAX+1)) .EQ. 0 )  IRET = IRET+1
      RETURN
C
C     RHO < .005;  WE CANNOT FIND P OR Q AND SO RETURN ONLY F, F'.
C
 850  FC(LMIN1) = F
      FCP(LMIN1) = R*F
      IRET = 2
      IF ( LMAX .EQ. LMIN )  RETURN
      DO 859  L = LMIN1, LMAX
         FC(L+1) = W*FC(L+1)
         FCP(L+1) = W*FCP(L+1)
 859  CONTINUE
      GO TO 840
C
C     F AND G ARE OUT OF THE MACHINE EXPONENT RANGE FOR LMIN.
C     IT WILL BE EVEN WORSE FOR  L > LMIN  SO GIVE UP AND RETURN
C
 900  IRET = 4
      GO TO 990
C
C     P + IQ FAILED TO CONVERGE
 920  IRET = 7
C
C     ERROR DETECTED, PRINT THE INPUT AND SOME STUFF
C
 990  write (6, 993) IRET, RHO, ETA, MINL, MAXL, ACCUR,
     1  RHOUSE, P, Q, R, T, X, I, SUM
 993  FORMAT ( 17H0***RCWFIN IRET =, I5, 6X, 7HINPUT =,
     1    2G20.10, 2I10, G15.5 /
     2  4H ***, 6G18.8 /  I8, G18.8 )
      RETURN
C
      END
